export const IPC_CHANNELS = {
	mainProcessMessage: "main-process-message",
	loadPreferences: "load-preferences",
	cameraError: "camera-error",
	cameraReady: "camera-ready",
	cameraCaptureStatus: "camera-capture-status",
	requestCameraCaptureStatus: "request-camera-capture-status",
	videoStream: "video-stream",
	cameraWindowClosed: "camera-window-closed",
	shortcutError: "shortcut-error",
	updateMessage: "update-message",
	updateExercisePrompt: "update-exercise-prompt",
	updateLookAwayCopy: "update-look-away-copy",
	updateColors: "update-colors",
	cameraMode: "camera-mode",
	faceTrackingData: "face-tracking-data",
	blinkDetected: "blink-detected",
	thresholdUpdated: "threshold-updated",
	playSound: "play-sound",
	stopSound: "stop-sound",
	currentPopupState: "current-popup-state",
	startBlinkReminders: "start-blink-reminders",
	stopBlinkReminders: "stop-blink-reminders",
	updateInterval: "update-interval",
	updateMicroBreakInterval: "update-micro-break-interval",
	updateBlinkPromptProfile: "update-blink-prompt-profile",
	updatePopupColors: "update-popup-colors",
	updatePopupTransparency: "update-popup-transparency",
	updateDarkMode: "update-dark-mode",
	updateCameraEnabled: "update-camera-enabled",
	updateCameraQuality: "update-camera-quality",
	updateCameraDevice: "update-camera-device",
	listCameraDevices: "list-camera-devices",
	cameraDevices: "camera-devices",
	cameraDeviceNotice: "camera-device-notice",
	updateAutoStopNoFaceEnabled: "update-auto-stop-no-face-enabled",
	updateAutoStopNoFaceMinutes: "update-auto-stop-no-face-minutes",
	updateSnoozeMinutes: "update-snooze-minutes",
	updateEarCalibration: "update-ear-calibration",
	updateClassifierCalibration: "update-classifier-calibration",
	startEarCalibration: "start-ear-calibration",
	cancelEarCalibration: "cancel-ear-calibration",
	earCalibrationProgress: "ear-calibration-progress",
	earCalibrationComplete: "ear-calibration-complete",
	calibrationNudge: "calibration-nudge",
	dismissCalibrationNudge: "dismiss-calibration-nudge",
	updateCalibrationNudgeEnabled: "update-calibration-nudge-enabled",
	updateEyeExercisesEnabled: "update-eye-exercises-enabled",
	updateExerciseInterval: "update-exercise-interval",
	updateExercisePrompts: "update-exercise-prompts",
	updateEyeCareIndependentOfTracking: "update-eye-care-independent-of-tracking",
	updateLookAwayEnabled: "update-look-away-enabled",
	updateLookAwayInterval: "update-look-away-interval",
	updateLookAwayDuration: "update-look-away-duration",
	updateLookAwayTitle: "update-look-away-title",
	updateLookAwayHint: "update-look-away-hint",
	updatePopupMessage: "update-popup-message",
	blinkClickThrough: "blink-click-through",
	updateBlinkPopupClickThrough: "update-blink-popup-click-through",
	updateKeyboardShortcuts: "update-keyboard-shortcuts",
	/** Unregister globals while the settings UI is capturing a new binding. */
	setShortcutCaptureMode: "set-shortcut-capture-mode",
	startCameraTracking: "start-camera-tracking",
	stopCameraTracking: "stop-camera-tracking",
	skipExercise: "skip-exercise",
	snoozeExercise: "snooze-exercise",
	skipLookAway: "skip-look-away",
	snoozeLookAway: "snooze-look-away",
	snoozeBlink: "snooze-blink",
	snoozeAll: "snooze-all",
	endPromptHush: "end-prompt-hush",
	updateMgdMode: "update-mgd-mode",
	showCameraWindow: "show-camera-window",
	closeCameraWindow: "close-camera-window",
	showPopupEditor: "show-popup-editor",
	popupEditorSaved: "popup-editor-saved",
	resetPreferences: "reset-preferences",
	updateSoundEnabled: "update-sound-enabled",
	updateSoundVolume: "update-sound-volume",
	updateNotificationStyle: "update-notification-style",
	updateSessionRecapEnabled: "update-session-recap-enabled",
	updateLaunchAtLogin: "update-launch-at-login",
	updateHasCompletedOnboarding: "update-has-completed-onboarding",
	audioFinished: "audio-finished",
	audioError: "audio-error",
	audioOutputInvalidated: "audio-output-invalidated",
	requestVideoStream: "request-video-stream",
	loadBlinkStats: "load-blink-stats",
	requestBlinkStats: "request-blink-stats",
	subscribeBlinkStats: "subscribe-blink-stats",
	unsubscribeBlinkStats: "unsubscribe-blink-stats",
	resetBlinkStats: "reset-blink-stats",
	updateQuietHoursEnabled: "update-quiet-hours-enabled",
	updateQuietHoursStart: "update-quiet-hours-start",
	updateQuietHoursEnd: "update-quiet-hours-end",
	updateQuietHoursByWeekday: "update-quiet-hours-by-weekday",
	updatePauseOnFullscreen: "update-pause-on-fullscreen",
	updatePauseAppRules: "update-pause-app-rules",
	listPauseAppCandidates: "list-pause-app-candidates",
	focusPauseState: "focus-pause-state",
	updateBlinkRateCoachingEnabled: "update-blink-rate-coaching-enabled",
	updateBlinkRateThreshold: "update-blink-rate-threshold",
	updateLocale: "update-locale",
	applyI18n: "apply-i18n",
	debugPreviewOverlay: "debug-preview-overlay",
	debugCleanPreview: "debug-clean-preview",
	debugPreviewSound: "debug-preview-sound",
	debugPreviewCheer: "debug-preview-cheer",
	debugPreviewLevelUp: "debug-preview-level-up",
	debugPreviewAchievement: "debug-preview-achievement",
	debugPreviewAchievementSummary: "debug-preview-achievement-summary",
	debugSetProfileLevel: "debug-set-profile-level",
	debugSetShopReward: "debug-set-shop-reward",
	debugSetShopDiscountLevel: "debug-set-shop-discount-level",
	startTraceRecording: "start-trace-recording",
	stopTraceRecording: "stop-trace-recording",
	openGithubRepo: "open-github-repo",
	openGithubReleases: "open-github-releases",
	openGithubReportIssue: "open-github-report-issue",
	openExternalUrl: "open-external-url",
	getReleaseNotes: "get-release-notes",
	checkForUpdates: "check-for-updates",
	autoUpdateStatus: "auto-update-status",
	installUpdate: "install-update",
	exportDiagnostics: "export-diagnostics",
	exportProfileImage: "export-profile-image",
	exportBackup: "export-backup",
	importBackup: "import-backup",
	listSettingsProfiles: "list-settings-profiles",
	saveSettingsProfile: "save-settings-profile",
	renameSettingsProfile: "rename-settings-profile",
	deleteSettingsProfile: "delete-settings-profile",
	switchSettingsProfile: "switch-settings-profile",
	updateGoalsConfig: "update-goals-config",
	spendBlinkReward: "spend-blink-reward",
	equipCheerTheme: "equip-cheer-theme",
	equipPopupPreset: "equip-popup-preset",
	shellReady: "shell-ready",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export const MAIN_RENDERER_RECEIVE_CHANNELS = [
	IPC_CHANNELS.mainProcessMessage,
	IPC_CHANNELS.loadPreferences,
	IPC_CHANNELS.cameraError,
	IPC_CHANNELS.cameraReady,
	IPC_CHANNELS.cameraCaptureStatus,
	IPC_CHANNELS.cameraDevices,
	IPC_CHANNELS.cameraDeviceNotice,
	IPC_CHANNELS.videoStream,
	IPC_CHANNELS.cameraWindowClosed,
	IPC_CHANNELS.updateMessage,
	IPC_CHANNELS.faceTrackingData,
	IPC_CHANNELS.blinkDetected,
	IPC_CHANNELS.thresholdUpdated,
	IPC_CHANNELS.earCalibrationProgress,
	IPC_CHANNELS.earCalibrationComplete,
	IPC_CHANNELS.calibrationNudge,
	IPC_CHANNELS.loadBlinkStats,
	IPC_CHANNELS.focusPauseState,
	IPC_CHANNELS.shortcutError,
	IPC_CHANNELS.autoUpdateStatus,
] as const;

export const MAIN_RENDERER_SEND_CHANNELS = [
	IPC_CHANNELS.startBlinkReminders,
	IPC_CHANNELS.stopBlinkReminders,
	IPC_CHANNELS.updateInterval,
	IPC_CHANNELS.updateMicroBreakInterval,
	IPC_CHANNELS.updateBlinkPromptProfile,
	IPC_CHANNELS.updatePopupColors,
	IPC_CHANNELS.updatePopupTransparency,
	IPC_CHANNELS.updateDarkMode,
	IPC_CHANNELS.updateCameraEnabled,
	IPC_CHANNELS.updateCameraQuality,
	IPC_CHANNELS.updateCameraDevice,
	IPC_CHANNELS.updateAutoStopNoFaceEnabled,
	IPC_CHANNELS.updateAutoStopNoFaceMinutes,
	IPC_CHANNELS.updateSnoozeMinutes,
	IPC_CHANNELS.updateEarCalibration,
	IPC_CHANNELS.updateClassifierCalibration,
	IPC_CHANNELS.startEarCalibration,
	IPC_CHANNELS.cancelEarCalibration,
	IPC_CHANNELS.updateEyeExercisesEnabled,
	IPC_CHANNELS.updateExerciseInterval,
	IPC_CHANNELS.updateExercisePrompts,
	IPC_CHANNELS.updateEyeCareIndependentOfTracking,
	IPC_CHANNELS.updateLookAwayEnabled,
	IPC_CHANNELS.updateLookAwayInterval,
	IPC_CHANNELS.updateLookAwayDuration,
	IPC_CHANNELS.updateLookAwayTitle,
	IPC_CHANNELS.updateLookAwayHint,
	IPC_CHANNELS.updatePopupMessage,
	IPC_CHANNELS.updateBlinkPopupClickThrough,
	IPC_CHANNELS.updateKeyboardShortcuts,
	IPC_CHANNELS.setShortcutCaptureMode,
	IPC_CHANNELS.startCameraTracking,
	IPC_CHANNELS.stopCameraTracking,
	IPC_CHANNELS.skipExercise,
	IPC_CHANNELS.snoozeExercise,
	IPC_CHANNELS.skipLookAway,
	IPC_CHANNELS.snoozeLookAway,
	IPC_CHANNELS.snoozeBlink,
	IPC_CHANNELS.snoozeAll,
	IPC_CHANNELS.endPromptHush,
	IPC_CHANNELS.updateMgdMode,
	IPC_CHANNELS.showCameraWindow,
	IPC_CHANNELS.closeCameraWindow,
	IPC_CHANNELS.showPopupEditor,
	IPC_CHANNELS.popupEditorSaved,
	IPC_CHANNELS.resetPreferences,
	IPC_CHANNELS.updateSoundEnabled,
	IPC_CHANNELS.updateSoundVolume,
	IPC_CHANNELS.updateNotificationStyle,
	IPC_CHANNELS.updateSessionRecapEnabled,
	IPC_CHANNELS.updateLaunchAtLogin,
	IPC_CHANNELS.updateHasCompletedOnboarding,
	IPC_CHANNELS.audioFinished,
	IPC_CHANNELS.requestVideoStream,
	IPC_CHANNELS.requestBlinkStats,
	IPC_CHANNELS.requestCameraCaptureStatus,
	IPC_CHANNELS.subscribeBlinkStats,
	IPC_CHANNELS.unsubscribeBlinkStats,
	IPC_CHANNELS.resetBlinkStats,
	IPC_CHANNELS.updateQuietHoursEnabled,
	IPC_CHANNELS.updateQuietHoursStart,
	IPC_CHANNELS.updateQuietHoursEnd,
	IPC_CHANNELS.updateQuietHoursByWeekday,
	IPC_CHANNELS.updatePauseOnFullscreen,
	IPC_CHANNELS.updatePauseAppRules,
	IPC_CHANNELS.updateBlinkRateCoachingEnabled,
	IPC_CHANNELS.updateBlinkRateThreshold,
	IPC_CHANNELS.updateCalibrationNudgeEnabled,
	IPC_CHANNELS.dismissCalibrationNudge,
	IPC_CHANNELS.updateLocale,
	IPC_CHANNELS.debugPreviewOverlay,
	IPC_CHANNELS.debugCleanPreview,
	IPC_CHANNELS.debugPreviewSound,
	IPC_CHANNELS.debugPreviewCheer,
	IPC_CHANNELS.debugPreviewLevelUp,
	IPC_CHANNELS.debugPreviewAchievement,
	IPC_CHANNELS.debugPreviewAchievementSummary,
	IPC_CHANNELS.debugSetProfileLevel,
	IPC_CHANNELS.debugSetShopReward,
	IPC_CHANNELS.debugSetShopDiscountLevel,
	IPC_CHANNELS.openGithubRepo,
	IPC_CHANNELS.openGithubReleases,
	IPC_CHANNELS.openGithubReportIssue,
	IPC_CHANNELS.openExternalUrl,
	IPC_CHANNELS.checkForUpdates,
	IPC_CHANNELS.installUpdate,
	IPC_CHANNELS.updateGoalsConfig,
	IPC_CHANNELS.spendBlinkReward,
	IPC_CHANNELS.equipCheerTheme,
	IPC_CHANNELS.equipPopupPreset,
	IPC_CHANNELS.shellReady,
] as const;

export const MAIN_RENDERER_INVOKE_CHANNELS = [
	IPC_CHANNELS.getReleaseNotes,
	IPC_CHANNELS.exportDiagnostics,
	IPC_CHANNELS.exportProfileImage,
	IPC_CHANNELS.exportBackup,
	IPC_CHANNELS.importBackup,
	IPC_CHANNELS.listSettingsProfiles,
	IPC_CHANNELS.saveSettingsProfile,
	IPC_CHANNELS.renameSettingsProfile,
	IPC_CHANNELS.deleteSettingsProfile,
	IPC_CHANNELS.switchSettingsProfile,
	IPC_CHANNELS.startTraceRecording,
	IPC_CHANNELS.stopTraceRecording,
	IPC_CHANNELS.listPauseAppCandidates,
	IPC_CHANNELS.listCameraDevices,
] as const;

/** Optional payload for {@link IPC_CHANNELS.snoozeAll}. */
export type SnoozeAllPayload = { useToken?: boolean };

/** True only when `useToken` is explicitly true. */
export function sanitizeSnoozeAllPayload(raw: unknown): boolean {
	if (raw === undefined || raw === null) return false;
	if (typeof raw !== "object") return false;
	return (raw as SnoozeAllPayload).useToken === true;
}
